2021-04-25-21:31:12-HKT back up

diff --git a/getbib b/getbib
--- a/getbib
+++ b/getbib
@@ -22,20 +22,20 @@ fi
 
 # Parse the arguments
 while [[ -n "$1" ]]; do
-	case "$1" in
-    -o|--output)
-        if [[ $# -gt 1 ]]; then
-            OUTPUTFILE="$2"
-            shift
-        fi
-        ;;
-	*)
-        if [[ -z "$AUXFILE" ]]; then
-            AUXFILE="$1"
-        fi
-        ;;
-	esac
-	shift
+    case "$1" in
+        -o|--output)
+            if [[ $# -gt 1 ]]; then
+                OUTPUTFILE="$2"
+                shift
+            fi
+            ;;
+        *)
+            if [[ -z "$AUXFILE" ]]; then
+                AUXFILE="$1"
+            fi
+            ;;
+    esac
+    shift
 done
 
 # Get the name of the aux file with full path.
@@ -85,64 +85,68 @@ touch "$BIBENTRIES" "$BIBMACROS"
 
 BIBDATAFILES=$(grep bibdata "$AUXFILE" | sed 's/.*\\\\bibdata{//' | sed 's/}.*$//' \
     | sed 's/,/\ /' | tr '\n' ' ')
-CITEDBIBS=$(grep bibcite "$AUXFILE" | sed 's/.*\\\\bibcite{//' | sed 's/}.*$//' | sort -u)
+    CITEDBIBS=$(grep bibcite "$AUXFILE" | sed 's/.*\\\\bibcite{//' | sed 's/}.*$//' | sort -u)
 
-CITEDBIBS_REDUCED="$CITEDBIBS"
-for FILE in $BIBDATAFILES
-do
-    CITEDBIBS="$CITEDBIBS_REDUCED"
-    for BIB in $CITEDBIBS
+    CITEDBIBS_REDUCED="$CITEDBIBS"
+    for FILE in $BIBDATAFILES
     do
-        if grep -q "@.*{\s*$BIB\s*," "$FILE" ; then
-            CITEDBIBS_REDUCED=$(echo "$CITEDBIBS_REDUCED" | sed "/^\s*$BIB\s*$/d")
-            BIBENTRY=$(sed -n "/@.*{\s*$BIB/,/^\s*}/{p;/^\s*}/q}" "$FILE")
-            echo "" >> "$BIBENTRIES"
-            echo "$BIBENTRY" >> "$BIBENTRIES"
-            BIBMACRO=$(echo "$BIBENTRY" | grep "journal\s*=\|journaltitle\s*=\|series\s*=" \
-                | sed 's/.*journal\s*=\s*//' \
-                | sed 's/.*journaltitle\s*=\s*//' \
-                | sed 's/.*series\s*=\s*//' \
-                | sed s/,.*$// | sed 's/{.*}//')
-            if [[ -n $BIBMACRO ]]; then
-                echo "" >> "$BIBMACROS"
-                grep "@string{\s*$BIBMACRO" "$FILE" | sed 's/.*@string/@string/' >> "$BIBMACROS"
+        CITEDBIBS="$CITEDBIBS_REDUCED"
+        for BIB in $CITEDBIBS
+        do
+            if grep -q "@.*{\s*$BIB\s*," "$FILE" ; then
+                CITEDBIBS_REDUCED=$(echo "$CITEDBIBS_REDUCED" | sed "/^\s*$BIB\s*$/d")
+                BIBENTRY=$(sed -n "/@.*{\s*$BIB/,/^\s*}/{p;/^\s*}/q}" "$FILE")
+                echo "" >> "$BIBENTRIES"
+                echo "$BIBENTRY" >> "$BIBENTRIES"
+                BIBMACRO=$(echo "$BIBENTRY" | grep "journal\s*=\|journaltitle\s*=\|series\s*=" \
+                    | sed 's/.*journal\s*=\s*//' \
+                    | sed 's/.*journaltitle\s*=\s*//' \
+                    | sed 's/.*series\s*=\s*//' \
+                    | sed s/,.*$// | sed 's/{.*}//')
+                                    if [[ -n $BIBMACRO ]]; then
+                                        echo "" >> "$BIBMACROS"
+                                        grep "@string{\s*$BIBMACRO" "$FILE" | sed 's/.*@string/@string/' >> "$BIBMACROS"
+                                    fi
             fi
-        fi
+        done
     done
-done
 
-if ! grep -q '[^[:space:]]' "$BIBENTRIES" ; then
-    echo ""
-    echo "$AUXFILE is not an aux file containing citations or it refers to invalid bib files. Abort."
-    echo ""
-    rm "$BIBENTRIES" "$BIBMACROS"
-    exit 3
+    if ! grep -q '[^[:space:]]' "$BIBENTRIES" ; then
+        echo ""
+        echo "$AUXFILE is not an aux file containing citations or it refers to invalid bib files. Abort."
+        echo ""
+        rm "$BIBENTRIES" "$BIBMACROS"
+        exit 3
+    fi
+
+    {
+        printf "%% bib file generated according to $AUXNAME.aux at $TIME.\n"
+        printf "%%\n"
+        printf "%% The recommended format of the bib entry label is:\n"
+        printf "%%\n"
+        printf "%%     <AuthorLastnames_YearLetter>\n"
+        printf "%%\n"
+        printf "%%  For example, the key for an article by Yuan may be:\n"
+        printf "%%\n"
+        printf "%%     Yuan_2000a\n%%\n"
+        printf "%% It is advised to use the abbreviations of names of serials in Math. Rev.\n"
+        printf "%% See https://mathscinet.ams.org/msnhtml/serials.pdf .\n"
+        printf "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n"
+    } > "$OUTPUTBIB"
+
+if grep -q '[^[:space:]]' "$BIBMACROS" ; then
+    {
+        printf "%% String macros for abbreviations of names of serials.\n"
+        printf "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MACRO_BEGIN%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n"
+
+        sed -r '/^\s*$/d' "$BIBMACROS" | sort -u
+        printf "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MACRO_END%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n"
+    } >> "$OUTPUTBIB"
 fi
+rm "$BIBMACROS"
 
-printf "%% bib file generated according to $AUXNAME.aux at "$TIME".\n" > $OUTPUTBIB
-printf "%%\n" >> $OUTPUTBIB
-printf "%% The recommended format of the bib entry label is:\n" >> $OUTPUTBIB
-printf "%%\n" >> $OUTPUTBIB
-printf "%%     <AuthorLastnames_YearLetter>\n" >> $OUTPUTBIB
-printf "%%\n" >> $OUTPUTBIB
-printf "%%  For example, the key for an article by Yuan may be:\n" >> $OUTPUTBIB
-printf "%%\n" >> $OUTPUTBIB
-printf "%%     Yuan_2000a\n%%\n" >> $OUTPUTBIB
-printf "%% It is advised to use the abbreviations of names of serials in Math. Rev.\n" >> $OUTPUTBIB
-printf "%% See https://mathscinet.ams.org/msnhtml/serials.pdf .\n" >> $OUTPUTBIB
-printf "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n" >> $OUTPUTBIB
-
-if grep -q '[^[:space:]]' $BIBMACROS ; then
-    printf "%% String macros for abbreviations of names of serials.\n" >> $OUTPUTBIB
-    printf "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MACRO_BEGIN%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n" >> $OUTPUTBIB
-
-    cat $BIBMACROS | sed -r '/^\s*$/d' | sort -u >> $OUTPUTBIB
-    printf "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MACRO_END%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n" >> $OUTPUTBIB
-fi
-rm $BIBMACROS
-
-cat $BIBENTRIES >> $OUTPUTBIB
-rm $BIBENTRIES
+cat "$BIBENTRIES" >> "$OUTPUTBIB"
+rm "$BIBENTRIES"
 
 
 # Make a backup of $OUTPUTFILE under $BAKDIR if $OUTPUTFILE exists.
@@ -151,49 +155,43 @@ BAKBIBFILE=$FULLBIBNAME-$TIME
 BIBDIFFERENT=0
 echo "" > $GETBIBLOG
 if [[ -f "$OUTPUTFILE" ]]; then
-    echo "******** Difference between the new bib and the original one ********" >> $GETBIBLOG
-    echo "" >> $GETBIBLOG
+    printf "******** Difference between the new bib and the original one ********\n" >> $GETBIBLOG
     # Remove the comments before comparing.
-    diff <(grep -v "^\s*%" $OUTPUTBIB) <(grep -v "^\s*%" $OUTPUTFILE) >> $GETBIBLOG
+    diff <(grep -v "^\s*%" "$OUTPUTBIB") <(grep -v "^\s*%" "$OUTPUTFILE") >> $GETBIBLOG
     if [[ $? -eq 1 ]]; then
         BIBDIFFERENT=1
         # $BAKDIR/$FULLBIBNAME-lastes_backup is always the latest backup.
         mkdir -p $BAKDIR
-        cp $OUTPUTFILE $BAKDIR/$FULLBIBNAME-latest_backup
-    	mv $OUTPUTFILE $BAKDIR/$BAKBIBFILE
+        cp "$OUTPUTFILE" "$BAKDIR/$FULLBIBNAME-latest_backup"
+        mv "$OUTPUTFILE" "$BAKDIR/$BAKBIBFILE"
         # Keep at most 50 latest files under $BAKDIR.
-        (cd $BAKDIR && ls -tp | grep -v '/$' | grep $FULLBIBNAME | tail -n +51 | xargs -I {} rm -- {})
+        (cd $BAKDIR && ls -tp | grep -v '/$' | grep "$FULLBIBNAME" | tail -n +51 | xargs -I {} rm -- {})
     fi
 fi
 
 # Write the output to $OUTPUTFILE
-mv $OUTPUTBIB $OUTPUTFILE
+mv "$OUTPUTBIB" "$OUTPUTFILE"
 
 
 # Check $OUTPUTFILE.
 # First, decide whether this is a BibLaTeX file or a BibTeX file.
-if grep -q "journaltitle\s*=\s*\|date\s*=\s*\|location\s*=\s*\|type\s*=\s*" $OUTPUTFILE ; then
+if grep -q "journaltitle\s*=\s*\|date\s*=\s*\|location\s*=\s*\|type\s*=\s*" "$OUTPUTFILE" ; then
     # This is likely a BibLaTeX file.
-    checkbib -l $OUTPUTFILE
+    checkbib -l "$OUTPUTFILE"
 else
     # This is likely a BibTeX file.
-    checkbib $OUTPUTFILE
+    checkbib "$OUTPUTFILE"
 fi
 
-echo "*************************** checkbib.log ****************************" | cat - $CHECKBIBLOG > tmp-$TIME && mv tmp-$TIME $CHECKBIBLOG
+echo "*************************** checkbib.log ****************************" | cat - "$CHECKBIBLOG" > "tmp-$TIME" && mv "tmp-$TIME" "$CHECKBIBLOG"
 cat $GETBIBLOG  >> $CHECKBIBLOG
 mv $CHECKBIBLOG $GETBIBLOG
 
 echo "Done. See $GETBIBLOG for $CHECKBIBLOG and the difference between the new bib and the original one."
 
 if [[ $BIBDIFFERENT -eq 1 ]]; then
-    echo ""
-    echo "A copy of the original bib file is saved at"
-    echo "$BAKDIR/$BAKBIBFILE"
-
-    echo "" >> $GETBIBLOG
-    echo "A copy of the original bib file is saved at" >> $GETBIBLOG
-    echo "$BAKDIR/$BAKBIBFILE" >> $GETBIBLOG
+    printf "\nA copy of the original bib file is saved at\n%s" "$BAKDIR/$BAKBIBFILE"
+    printf "\nA copy of the original bib file is saved at\n%s" "$BAKDIR/$BAKBIBFILE" >> $GETBIBLOG
 fi
 
 echo ""
